##### Configuration #####
triggerNum_List = $MLB$ { HLT_HICsAK4PFJet60Eta1p5_v1,
                          HLT_HICsAK4PFJet80Eta1p5_v1,
                          HLT_HICsAK4PFJet100Eta1p5_v1,
                          HLT_HICsAK4PFJet120Eta1p5_v1 } $MLE$
# global denominator, list of triggers that define the subset of events to consider. These triggers will be "OR"ed.
triggerDenomGlobal_List = {HLT_HICsAK4PFJet60Eta1p5_v1}
# individual denominators
triggerDenom_List = $MLB$ {} $MLE$
triggerNumPrescl_List = $MLB$ { HLT_HICsAK4PFJet60Eta1p5_v1_Prescl,
                                HLT_HICsAK4PFJet80Eta1p5_v1_Prescl,
                                HLT_HICsAK4PFJet100Eta1p5_v1_Prescl, 
                                HLT_HICsAK4PFJet120Eta1p5_v1_Prescl } $MLE$
triggerDenomPrescl_List = {HLT_HICsAK4PFJet60Eta1p5_v1_Prescl}
treePath = ggHiNtuplizer/EventTree     # path of the object tree
# collision types : HI, HIMC, PP, PPMC, PA, PAMC, HI2018, HIMC2018
collisionType = 3
# Run and lumiSection range to process
treeSelectionBase = {} # {Run1, lumiStart1, lumiEnd1;;; Run2, lumiStart2, lumiEnd2}
doEventWeight = 0
