#+title: ~triggerAnalysis~ README

* Purpose of this code

The purpose of this code is to analyze trigger efficiency for the high-level trigger system in CMS.
This code requires the simulated analysis-object data (~AOD~) and the emulated HLT trigger decicision data (~openHLT~).
In the current version of this code, these data are inputed as single files.
Therefore, full forests of ~AOD~ and output of ~openHLT~ must be merged into a single file for the code to run properly.
The reason for this requirement is because the ~run-lumi-event~ map, which is used to match ~AOD~ and ~openHLT~ events (events are not in the same order between the two data types), which is required to calculate the trigger efficiency.


* How to run

The code to run here is ~triggerAnalysisSimple.C~.  This is a simplified version of an outdated trigger analyzer.

After the necessary files are obtained, run the code as follows:

#+BEGIN_SRC sh
  root -l 'triggerAnalysisSimple("/path/to/openHLT.root","/path/to/AOD.root","/path/to/output.root")'
#+END_SRC

